# Generated by Django 5.1 on 2024-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_invitation', models.CharField(max_length=255)),
                ('second_invitation', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('accepted', 'Приду'), ('declined', 'Не приду'), ('pending', 'Ожидание')], default='pending', max_length=10)),
                ('token', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
