# Generated by Django 5.1 on 2024-08-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='second_invitation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
