# Generated by Django 5.1 on 2024-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_alter_invitation_second_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='wish',
            field=models.TextField(blank=True, null=True, verbose_name='пожелания'),
        ),
    ]
